name: Deploy on AWS

on: 
  workflow_dispatch:  # this has to be triggered manually

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh-pipeline
        uses: cross-the-world/ssh-pipeline@v1.2.0
        with:
          host: ${{ secrets.HOSTNAME }}
          user: ec2-user
          key: ${{ secrets.LABSUSERPEM }}
          script: |
            cd /home/ec2-user/cost_sharing
            ./redeploy.sh
