name: Static Analysis
on: [push, pull_request]

jobs:
  static-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 # Checkout the repository content to github runner.

      - name: Setup Repo & Environment
        uses: ./.github/actions/setup_venv

      - name: Execute Static Analysis
        run: .venv/bin/pylint src tests

